[package]
name = "remindy-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Axum and Tower-http handle the webinterface-rest-api
axum = { version = "0.6.2", features = ['multipart'] }
tower-http = { version = "0.4.3", features = ['cors'] }
