[package]
name = "i3blocks_client"
version = "0.1.0"
edition = "2021"

[dependencies]
reminder = { path = "../reminder" }
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
config = { path = "../config" }

[lints]
workspace = true
