on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: sudo apt install openssl && sudo apt install libssl-dev && sudo apt install cmake && sudo apt install gtk-3-dev
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
